feat: PR用テンプレートを追加
kufu/textlint-rule-preset-smarthr pull request #14
Opened 2021-04-13 03:49 UTC by kgsi

## 課題・背景

* PR用のテンプレートがないので、PRを出すときにフォーマットをコピペしてる。
* テンプレートを用意して簡略化したい。

## やったこと

* GitHubのPR用テンプレートを追加しました。

2021-04-14 10:04 UTC, otapo requested changes
項目として、「正しいと判定される想定の文章」「誤りと判定される想定の文章」があると、確認しやすそうです。

2021-04-20 15:49 UTC, kgsi commented
> 項目として、「正しいと判定される想定の文章」「誤りと判定される想定の文章」があると、確認しやすそうです。

@otapo 承知です！修正してみましたので、確認をお願いします。

2021-04-26 11:25 UTC, diescake commented
このPRは @otapo san の一存に委任する姿勢です！！🙏

2021-04-26 22:50 UTC, otapo approved these changes
👍

2021-04-26 22:57 UTC, merged