feat: huskyとcommitlintを追加
kufu/textlint-rule-preset-smarthr pull request #61
Opened 2021-06-14 11:32 UTC by kgsi

## 課題・背景

- コミットメセージのルールが誤っている場合、訂正指示を指摘してくれる仕組みがない
- v1.4.0更新時にメッセージルールからこぼれた結果、CHANGELOG更新漏れが発生してしまった

## やったこと

- huskyの導入
- commit時に[メッセージルール](https://www.conventionalcommits.org/en/v1.0.0/)を守っていない場合、コミットできないようにする

## やらなかったこと

## 動作確認

### 正しいと判定される想定の文章

### 誤りと判定される想定の文章

2021-06-28 09:51 UTC, diescake commented
ぐおー完全に見落としてました！🙇🙇

2021-06-28 09:54 UTC, diescake commented
@kgsi 

なんか yarn.lock の差分がとてつもないことになっているので、
ライブラリを追加し直してみた方がよいかもしれません…！🙏

![image](https://user-images.githubusercontent.com/5195381/123617182-f502b000-d841-11eb-8b4d-c1608f61427a.png)

2021-06-28 10:03 UTC, diescake commented
ローカルで試してみたんですが、
hook されないっぽくて適当なコミットログでもコミットできちゃいました😭

husky v6 の仕様全くわかってなくてアレなんですが、確認をお願いできますでしょうか！🙏

2021-08-03 01:51 UTC, diescake requested changes
（PR整理中… レビュー済みの状態なので一旦 `Request changes` に変更しておきますねー）

2021-08-17 01:35 UTC, kgsi commented
@diescake すみません！このPR、時間が空きすぎてhusky自体のversionも上がってしまったので一度閉じます。別のPRで再度PRを上げ直しますねmm

2021-08-17 02:24 UTC, closed without merging